# Generated by Django 5.1 on 2024-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_credits',
            field=models.IntegerField(default=100000),
        ),
    ]
