# Generated by Django 5.1 on 2025-07-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_api_key',
            field=models.CharField(blank=None, max_length=200, null=True),
        ),
    ]
