# Generated by Django 5.1 on 2024-12-16 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_writing_tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QABox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qaBox', to='ai_writing_tools.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaBoxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('embeddings', models.JSONField(default=list)),
                ('paragraphs', models.JSONField()),
                ('text_source', models.TextField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('wiki', 'wiki'), ('pdf', 'pdf'), ('youtube', 'youtube'), ('audio', 'audio'), ('video', 'video')], default='Text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projects', models.ManyToManyField(related_name='resources', to='ai_writing_tools.project')),
                ('qaBoxes', models.ManyToManyField(related_name='resources', to='QA_box.qabox')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.TextField()),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qaBox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qamessages', to='QA_box.qabox')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qamessages', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QA_box.resource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
