# Generated by Django 5.1 on 2024-10-16 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_writing_tools', '0007_remove_resource_qaboxes_remove_qamessage_qabox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QABox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaBoxes', to='ai_writing_tools.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaBoxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('embeddings', models.JSONField()),
                ('paragraphs', models.JSONField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('PDF', 'PDF'), ('Youtube', 'Youtube'), ('Audio', 'Audio'), ('Video', 'Video')], default='Text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(blank=True, null=True, related_name='resources', to='ai_writing_tools.project')),
                ('qaBoxes', models.ManyToManyField(related_name='resources', to='QA_box.qabox')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QAMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('answer', models.TextField()),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qaBox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qamessages', to='QA_box.qabox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qamessages', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QA_box.resource')),
            ],
        ),
    ]
