# Generated by Django 5.1 on 2025-01-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='text_source',
            field=models.TextField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
