# Generated by Django 5.1 on 2024-10-16 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='qabox',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='qamessage',
            name='qaBox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qamessages', to='QA_box.qabox'),
        ),
        migrations.AlterField(
            model_name='qamessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qamessages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='embeddings',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
