# Generated by Django 5.1 on 2024-10-19 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0002_rename_title_resource_name_remove_qabox_modified_at_and_more'),
        ('ai_writing_tools', '0007_remove_resource_qaboxes_remove_qamessage_qabox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabox',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qaBoxes', to='ai_writing_tools.project'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='projects',
            field=models.ManyToManyField(related_name='resources', to='ai_writing_tools.project'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('wiki', 'wiki'), ('pdf', 'pdf'), ('youtube', 'youtube'), ('audio', 'audio'), ('video', 'video')], default='Text', max_length=10),
        ),
    ]
