# Generated by Django 5.1 on 2025-01-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0002_alter_resource_text_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='text_source',
            field=models.TextField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
