# Generated by Django 5.1 on 2024-10-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0003_alter_qabox_project_alter_resource_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='source',
        ),
        migrations.AddField(
            model_name='resource',
            name='text_source',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
