# Generated by Django 5.1 on 2025-03-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_box', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qabox',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
