# Generated by Django 5.1 on 2025-05-24 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('lang', models.CharField(default='en', max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('article', models.JSONField()),
                ('article_text', models.TextField(default='')),
                ('outline', models.JSONField(default=list)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('used_credits', models.IntegerField(default=0)),
                ('chatbox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ai_chat.chatbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Excalidraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('elements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excalidraws', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excalidraws', to='ai_writing_tools.project')),
            ],
        ),
        migrations.CreateModel(
            name='TextCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(max_length=255)),
                ('is_sentence', models.BooleanField(default=False)),
                ('original_text', models.TextField()),
                ('completion_text', models.TextField(null=True)),
                ('n_prompt_tokens', models.IntegerField(default=0)),
                ('n_gen_tokens', models.IntegerField(default=0)),
                ('used_credits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textcompletions', to='ai_writing_tools.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textcompletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextImprovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('used_credits', models.IntegerField(default=0)),
                ('model_name', models.CharField(max_length=255)),
                ('improved_text', models.TextField()),
                ('original_text', models.TextField()),
                ('n_prompt_tokens', models.IntegerField(default=0)),
                ('n_gen_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textimprovements', to='ai_writing_tools.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textimprovements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
