# Generated by Django 5.1 on 2024-09-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textcompletion',
            old_name='n_tokens',
            new_name='n_gen_tokens',
        ),
        migrations.RenameField(
            model_name='textimprovement',
            old_name='n_tokens',
            new_name='n_gen_tokens',
        ),
        migrations.AddField(
            model_name='textcompletion',
            name='n_prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textimprovement',
            name='n_prompt_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
