# Generated by Django 5.1 on 2024-08-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textimprovement',
            name='n_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='lang',
            field=models.CharField(default='en', max_length=3),
        ),
    ]
