# Generated by Django 5.1 on 2025-07-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='article',
            field=models.JSONField(default=[{'text': ''}]),
        ),
    ]
