# Generated by Django 5.1 on 2025-01-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0002_excalidraw_project_excalidraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='excalidraw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='excalidraw',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='excalidraw',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ai_writing_tools.excalidraw'),
        ),
    ]
