# Generated by Django 5.1 on 2024-10-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0002_rename_n_tokens_textcompletion_n_gen_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcompletion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textcompletions', to='ai_writing_tools.project'),
        ),
    ]
