# Generated by Django 5.1 on 2025-01-18 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0003_excalidraw_created_at_excalidraw_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='excalidraw',
        ),
        migrations.AddField(
            model_name='excalidraw',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excalidraw', to='ai_writing_tools.project'),
        ),
    ]
