# Generated by Django 5.1 on 2025-03-23 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0004_remove_project_excalidraw_excalidraw_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidraw',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excalidraw', to='ai_writing_tools.project'),
        ),
        migrations.AlterField(
            model_name='textcompletion',
            name='model_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='textimprovement',
            name='model_name',
            field=models.CharField(max_length=255),
        ),
    ]
