# Generated by Django 5.1 on 2024-10-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0004_qabox_qamessage_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qamessage',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='qamessage',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_writing_tools.resource'),
        ),
    ]
