# Generated by Django 5.1 on 2024-10-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0005_remove_qamessage_modified_at_qamessage_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='qaBoxes',
            field=models.ManyToManyField(related_name='resources', to='ai_writing_tools.qabox'),
        ),
    ]
