# Generated by Django 5.1 on 2025-03-23 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0005_alter_excalidraw_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excalidraw',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excalidraws', to='ai_writing_tools.project'),
        ),
    ]
