# Generated by Django 5.1 on 2024-10-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_writing_tools', '0006_alter_resource_qaboxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='qaBoxes',
        ),
        migrations.RemoveField(
            model_name='qamessage',
            name='qaBox',
        ),
        migrations.RemoveField(
            model_name='qamessage',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='qamessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.DeleteModel(
            name='QABox',
        ),
        migrations.DeleteModel(
            name='QAMessage',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
